### ISSUE TITLE
description for class String contains details hidden when parsed as Commonmark

### ISSUE THREAD

**Issue by jonassmedegaard** [ontola/atomic-data#30]
At https://atomicdata.dev/datatypes/string it says
> Allows newlines with .

Source reveals that it is talking about a newline surrounded by backticks.

Seems the description field should escape those backticks to avoid them being parsed as a Commonmark code block.

Alternatively, perhaps this is a bug in the Atomic Data Browser that it parses plaintext description as Commonmark?

**Comment by joepio** [comment]
Nice find, thanks!
